#!/usr/bin/env python3
"""Which key combinations the MacBook Pro 2021 built-in keyboard registers.

Library:
    import kbmatrix
    kb = kbmatrix.load()                        # data/macbookpro18-1-iso.json (measured)
    kb.registers(["J", "H", "M"])               # False
    kb.explain(["J", "H", "M"])                 # why
    kb.dropped_when_holding("J", "M")           # keys that can't be added to J+M
    us = kbmatrix.load(kbmatrix.ANSI_DATA)      # the US (ANSI) keyboard, derived from the ISO one (not measured)

Command line:
    python3 kbmatrix.py check J H M
    python3 kbmatrix.py --layout us check J H M
    python3 kbmatrix.py hold J M
    python3 kbmatrix.py triples [--csv]
    python3 kbmatrix.py validate [-v]
    python3 kbmatrix.py keys
    python3 kbmatrix.py build                   # regenerate docs/ and the derived US data

Standard library only.
"""

import argparse
import csv
import html
import io
import itertools
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")
DEFAULT_DATA = os.path.join(DATA, "macbookpro18-1-iso.json")
ANSI_DATA = os.path.join(DATA, "macbookpro18-1-ansi.json")   # generated by `build` from DEFAULT_DATA
LAYOUT_DATA = {"iso": DEFAULT_DATA, "ansi": ANSI_DATA}
LAYOUT_NAMES = {"iso": "Canadian French (ISO)", "ansi": "US (ANSI)"}
OBSERVATIONS = os.path.join(DATA, "observations")
DOCS = os.path.join(HERE, "docs")

# Observation files used to work out the wiring, and files predicted before they were run.
FITTED = ["1-matrix-scan.txt", "2-wiring-check-1.txt"]
PREDICTED = ["3-wiring-check-2.txt", "4-by-hand.txt"]

# Extra names accepted on the command line (case-insensitive).
ALIASES = {
    "grave": "Grave", "backtick": "Grave", "backquote": "Grave", "`": "Grave",
    "minus": "Minus", "-": "Minus", "dash": "Minus",
    "equal": "Equal", "equals": "Equal", "=": "Equal",
    "lbracket": "LBracket", "leftbracket": "LBracket", "bracketleft": "LBracket", "[": "LBracket",
    "rbracket": "RBracket", "rightbracket": "RBracket", "bracketright": "RBracket", "]": "RBracket",
    "backslash": "Backslash", "\\": "Backslash",
    "semicolon": "Semicolon", ";": "Semicolon",
    "quote": "Quote", "apostrophe": "Quote", "'": "Quote",
    "comma": "Comma", ",": "Comma",
    "period": "Period", "dot": "Period", ".": "Period",
    "slash": "Slash", "/": "Slash",
    "space": "Space", "spacebar": "Space", " ": "Space",
}


class Matrix:
    def __init__(self, data):
        self.data = data
        self.layout = data.get("layout", "iso")  # physical layout, for the drawings: "iso" or "ansi"
        self.rows = [r["id"] for r in data["rows"]]
        self.columns = [c["id"] for c in data["columns"]]
        self.keys = {k["id"]: k for k in data["keys"]}
        self.order = [k["id"] for k in data["keys"]]
        self.pos = {k["id"]: (k["row"], k["column"]) for k in data["keys"]}
        self.at = {p: k for k, p in self.pos.items()}
        self.unidentified = {(u["row"], u["column"]) for u in data["unidentified"]}
        self.spot_notes = {(u["row"], u["column"]): u["note"] for u in data["unidentified"] if u.get("note")}
        # Keys the keyboard has but whose place in the matrix is not known (the derived US keyboard's ` and \).
        self.unplaced = {k["id"]: k for k in data.get("unplaced", [])}
        self.occupied = set(self.at) | self.unidentified
        self.rollover = data.get("rollover")  # the most keys registered at once (None: no limit known)
        if len(self.at) != len(self.pos):
            raise ValueError("two keys share a spot")
        if self.unidentified & set(self.at):
            raise ValueError("an unidentified spot holds a known key")
        if set(self.unplaced) & set(self.keys):
            raise ValueError("a key is both placed and unplaced")
        # Names, most specific first: ids and labels, then aliases, kVK constants and web codes.
        # Key codes need a prefix ("code:5" is G), since digits are key names.
        named = data["keys"] + data.get("unplaced", [])
        self._names = {}
        for k in named:
            for n in (k["kvk"], k["web_code"]):
                self._names[n.lower()] = k["id"]
        for a, k in ALIASES.items():
            if k in self.keys or k in self.unplaced:
                self._names[a] = k
        for k in named:
            self._names[k["label"].lower()] = k["id"]
            self._names[k["id"].lower()] = k["id"]
        self._codes = {k["keycode"]: k["id"] for k in named}

    # Names

    def key(self, token):
        """Key id for a name or label ("J", "5", ";", "semicolon"), a kVK_ constant, a web KeyboardEvent.code
        ("KeyJ"), or a macOS key code written "code:38"."""
        t = str(token)
        if t in self.keys:
            return t
        if t.lower().startswith("code:"):
            k = self._codes.get(int(t[5:]))
        else:
            k = self._names.get(t.lower()) or self._names.get(t)
        if k in self.unplaced:
            u = self.unplaced[k]
            raise KeyError(f"{u['label']} is not placed in this keyboard's matrix: {u['note']}")
        if k is None:
            raise KeyError(f"unknown key {token!r} (try: python3 kbmatrix.py keys)")
        return k

    def keys_of(self, tokens):
        """Key ids for a list of names; a name may also be several names joined with spaces or '+'."""
        out = []
        for t in tokens:
            parts = [t] if t in self.keys or t.lower() in self._names else t.replace("+", " ").split()
            for part in parts:
                k = self.key(part)
                if k not in out:
                    out.append(k)
        return out

    def label(self, k):
        return self.keys[k]["label"]

    # The rule

    def shares(self, a, b):
        (ra, ca), (rb, cb) = self.pos[a], self.pos[b]
        return ra == rb or ca == cb

    def l_shape(self, a, b, c):
        """(corner key, fourth-corner spot) if the three keys form an L, else None."""
        for x, y, z in ((a, b, c), (b, a, c), (c, a, b)):
            if self.shares(y, z):
                continue
            (rx, cx), (ry, cy), (rz, cz) = self.pos[x], self.pos[y], self.pos[z]
            if rx == ry and cx == cz:
                return x, (rz, cy)
            if cx == cy and rx == rz:
                return x, (ry, cz)
        return None

    def triple_blocked(self, a, b, c):
        s = self.l_shape(a, b, c)
        return s is not None and s[1] in self.occupied

    def blocked_triples(self, keys):
        """Every 3-key part of `keys` the keyboard drops, as (triple, corner, fourth spot)."""
        keys = self.keys_of(keys)
        out = []
        for t in itertools.combinations(keys, 3):
            s = self.l_shape(*t)
            if s and s[1] in self.occupied:
                out.append((t, s[0], s[1]))
        return out

    def too_many(self, keys):
        return self.rollover is not None and len(keys) > self.rollover

    def registers(self, keys):
        keys = self.keys_of(keys)
        return not self.too_many(keys) and not self.blocked_triples(keys)

    def occupant(self, spot):
        if spot in self.at:
            return self.label(self.at[spot])
        if spot in self.spot_notes:
            return f"an unknown key ({self.spot_notes[spot]})"
        if spot in self.unidentified:
            return "an unidentified key (not a letter, digit, punctuation or space key)"
        return None

    def explain(self, keys):
        keys = self.keys_of(keys)
        names = " + ".join(self.label(k) for k in keys)
        bad = self.blocked_triples(keys)
        if len(keys) < 3:
            return f"{names}: registers (any one or two keys always do)."
        if self.too_many(keys):
            return f"{names}: dropped: the keyboard registers at most {self.rollover} keys at once."
        if not bad:
            ls = [t for t in itertools.combinations(keys, 3) if self.l_shape(*t)]
            text = f"{names}: registers."
            for t in ls:
                corner, spot = self.l_shape(*t)
                text += (f"\n  {'+'.join(self.label(x) for x in t)} is an L (corner {self.label(corner)}), but the "
                         f"fourth corner (row {spot[0]}, column {spot[1]}) is an empty spot.")
            return text
        text = f"{names}: dropped by the keyboard ({len(bad)} bad 3-key part{'s' if len(bad) > 1 else ''})."
        for t, corner, spot in bad:
            others = [x for x in t if x != corner]
            rc = self.pos[corner]
            row_mate = next(x for x in others if self.pos[x][0] == rc[0])
            col_mate = next(x for x in others if self.pos[x][1] == rc[1])
            text += (f"\n  {self.label(corner)} shares row '{rc[0]}' with {self.label(row_mate)} and column "
                     f"'{rc[1]}' with {self.label(col_mate)}; the fourth corner (row {spot[0]}, column {spot[1]}) "
                     f"holds {self.occupant(spot)}.")
        return text

    def dropped_when_holding(self, a, b):
        a, b = self.key(a), self.key(b)
        return [x for x in self.order if x not in (a, b) and self.triple_blocked(a, b, x)]

    def all_blocked_triples(self):
        out = []
        for t in itertools.combinations(self.order, 3):
            s = self.l_shape(*t)
            if s and s[1] in self.occupied:
                out.append((t, s[0], s[1]))
        return out

    def never_blocking(self):
        """Keys that are not part of any dropped 3-key combination."""
        used = set()
        for t, _, _ in self.all_blocked_triples():
            used.update(t)
        return [k for k in self.order if k not in used]

    def spot_states(self, observations):
        """For every spot: 'key', 'unidentified', 'empty' (seen empty as a fourth corner) or 'unknown'."""
        seen_empty = set()
        for ob in observations:
            if ob.blocked:
                continue
            for t in itertools.combinations(ob.keys, 3):
                s = self.l_shape(*t)
                if s and s[1] not in self.occupied:
                    seen_empty.add(s[1])
        out = {}
        for r in self.rows:
            for c in self.columns:
                p = (r, c)
                out[p] = ("key" if p in self.at else "unidentified" if p in self.unidentified
                          else "empty" if p in seen_empty else "unknown")
        return out

    def open_spots(self, observations):
        """Unknown spots that decide whether some combination of known keys registers."""
        states = self.spot_states(observations)
        need = set()
        for t in itertools.combinations(self.order, 3):
            s = self.l_shape(*t)
            if s and states[s[1]] == "unknown":
                need.add(s[1])
        return sorted(need)


def load(path=DEFAULT_DATA):
    with open(path, encoding="utf-8") as f:
        return Matrix(json.load(f))


# The US (ANSI) keyboard --------------------------------------------------------------------------------------

# The two mapped keys that are somewhere else on an ANSI keyboard, and where.
ANSI_MOVED = {
    "Grave": "on US keyboards ` is left of 1, where ISO keyboards have §, and its wires were not measured",
    "Backslash": "on US keyboards \\ is above Return, where ISO keyboards have the top of Return, and its wires were "
                 "not measured",
}
ANSI_ROWS = {
    "space": "Space and ' (ISO keyboards also have ` here); the unidentified keys here are probably modifiers",
    "bracket": "[ and ] (ISO keyboards also have \\ here)",
}


def derive_ansi(iso):
    """The US (ANSI) keyboard of the same model, derived from the measured ISO data. Not measured: the 46 keys
    that are in the same place on both layouts keep their ISO wires; ` and \\, which are elsewhere on ANSI
    keyboards, are left unplaced; the spots of the ISO ` and \\ keys still count as keys, so every combination
    of the other keys that the ISO keyboard drops is predicted to drop here too."""
    moved = [k for k in iso["keys"] if k["id"] in ANSI_MOVED]
    spots = [{"row": k["row"], "column": k["column"],
              "note": f"ISO keyboards have {k['label']} here; not measured on US keyboards, so counted as a key"}
             for k in moved]
    rank = {r["id"]: i for i, r in enumerate(iso["rows"])}, {c["id"]: i for i, c in enumerate(iso["columns"])}
    device = {k: v for k, v in iso["device"].items() if k != "measured"}
    device["keyboard"] = "built-in, US (ANSI); not measured, derived from the ISO measurement of the same model"
    return {
        "schema": iso["schema"],
        "layout": "ansi",
        "device": device,
        "derived_from": os.path.basename(DEFAULT_DATA),
        "basis": ("Not measured. This is the ISO wiring, assuming that the 46 keys in the same place on both layouts "
                  "keep their wires. ` and \\ are elsewhere on US keyboards, so they are left out (see unplaced). "
                  "The spots of the ISO ` and \\ keys still count as keys (see unidentified), so every combination "
                  "of the other keys that the ISO keyboard drops is predicted to drop here too."),
        "rule": iso["rule"],
        "rollover": iso["rollover"],
        "columns": iso["columns"],
        "rows": [dict(r, description=ANSI_ROWS.get(r["id"], r["description"])) for r in iso["rows"]],
        "keys": [k for k in iso["keys"] if k["id"] not in ANSI_MOVED],
        "unplaced": [{"id": k["id"], "label": k["label"], "keycode": k["keycode"], "kvk": k["kvk"],
                      "web_code": k["web_code"], "note": ANSI_MOVED[k["id"]]} for k in moved],
        "unidentified": sorted(iso["unidentified"] + spots, key=lambda u: (rank[0][u["row"]], rank[1][u["column"]])),
    }


# Observations -------------------------------------------------------------------------------------------------

class Observation:
    def __init__(self, keys, blocked, label, source):
        self.keys = keys
        self.blocked = blocked
        self.label = label
        self.source = source


def parse_observations(path, kb):
    """Reads a Matrix Scan / Wiring Check report: one observation per tapped key, one per combination."""
    name = os.path.basename(path)
    all_keys = None
    out = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            fields = line.split("#", 1)[0].split()
            if not fields:
                continue
            head = fields[0]
            if head == "keys":
                all_keys = [kb.key(x) for x in fields[1:]]
            elif head == "sweep":
                a, b = [kb.key(x) for x in fields[1].split("+")]
                rest = fields[3:]
                split = next((i for i, x in enumerate(rest) if x in ("untested", "tapped")), len(rest))
                blocked = set() if rest[:split] == ["-"] else {kb.key(x) for x in rest[:split]}
                if split < len(rest):
                    listed = [kb.key(x) for x in rest[split + 1:]]
                    tapped = listed if rest[split] == "tapped" else [k for k in all_keys if k not in listed and k not in (a, b)]
                else:
                    tapped = [k for k in all_keys if k not in (a, b)]
                for x in tapped:
                    out.append(Observation([a, b, x], x in blocked,
                                           f"hold {kb.label(a)}+{kb.label(b)}, tap {kb.label(x)}", name))
            elif head == "combo":
                ks = [kb.key(x) for x in fields[1].split("+")]
                out.append(Observation(ks, fields[2] == "fail", "press " + "+".join(kb.label(k) for k in ks), name))
    return out


def all_observations(kb, files=None):
    files = files or (FITTED + PREDICTED)
    obs = []
    for f in files:
        obs += parse_observations(os.path.join(OBSERVATIONS, f), kb)
    return obs


def validate(kb, files=None):
    """(explained, total, mismatches) for the given observation files."""
    obs = all_observations(kb, files)
    bad = [o for o in obs if kb.registers(o.keys) == o.blocked]
    return len(obs) - len(bad), len(obs), bad


# Physical keyboards (ISO and US ANSI), in key units -----------------------------------------------------------

def _keyboard(middle):
    """(label, x, y, w, h, key id or None) for every key: the function row, the rows `middle` adds, the bottom row."""
    k = []

    def add(label, x, y, w=1.0, h=1.0, kid=None):
        k.append((label, x, y, w, h, kid))

    def row(y, x0, items):
        for i, (label, kid) in enumerate(items):
            add(label, x0 + i, y, kid=kid)

    add("esc", 0, 0, 1.5, 0.6)
    for i in range(12):
        add(f"F{i + 1}", 1.5 + i, 0, 1, 0.6)
    add("Touch ID", 13.5, 0, 1, 0.6)
    middle(add, row)
    add("fn", 0, 4.7)
    add("control", 1, 4.7)
    add("option", 2, 4.7)
    add("command", 3, 4.7, 1.25)
    add("space", 4.25, 4.7, 5, kid="Space")
    add("command", 9.25, 4.7, 1.25)
    add("option", 10.5, 4.7)
    add("←", 11.5, 4.7)
    add("↑", 12.5, 4.7, 1, 0.5)
    add("↓", 12.5, 5.2, 1, 0.5)
    add("→", 13.5, 4.7)
    return k


def iso_keyboard():
    """(label, x, y, w, h, key id or None). The ISO Return key is drawn separately (RETURN_PATH)."""
    def middle(add, row):
        row(0.7, 0, [("§", None)] + [(d, d) for d in "1234567890"] + [("-", "Minus"), ("=", "Equal")])
        add("delete", 13, 0.7, 1.5)
        add("tab", 0, 1.7, 1.5)
        row(1.7, 1.5, [(c, c) for c in "QWERTYUIOP"] + [("[", "LBracket"), ("]", "RBracket")])
        add("caps lock", 0, 2.7, 1.75)
        row(2.7, 1.75, [(c, c) for c in "ASDFGHJKL"] + [(";", "Semicolon"), ("'", "Quote"), ("\\", "Backslash")])
        add("shift", 0, 3.7, 1.25)
        row(3.7, 1.25, [("`", "Grave")] + [(c, c) for c in "ZXCVBNM"] + [(",", "Comma"), (".", "Period"), ("/", "Slash")])
        add("shift", 12.25, 3.7, 2.25)
    return _keyboard(middle)


def ansi_keyboard():
    """(label, x, y, w, h, key id or None). ` is left of 1, \\ above Return, Return one row tall, a wide left
    Shift and no key between it and Z."""
    def middle(add, row):
        row(0.7, 0, [("`", "Grave")] + [(d, d) for d in "1234567890"] + [("-", "Minus"), ("=", "Equal")])
        add("delete", 13, 0.7, 1.5)
        add("tab", 0, 1.7, 1.5)
        row(1.7, 1.5, [(c, c) for c in "QWERTYUIOP"] + [("[", "LBracket"), ("]", "RBracket"), ("\\", "Backslash")])
        add("caps lock", 0, 2.7, 1.75)
        row(2.7, 1.75, [(c, c) for c in "ASDFGHJKL"] + [(";", "Semicolon"), ("'", "Quote")])
        add("return", 12.75, 2.7, 1.75)
        add("shift", 0, 3.7, 2.25)
        row(3.7, 2.25, [(c, c) for c in "ZXCVBNM"] + [(",", "Comma"), (".", "Period"), ("/", "Slash")])
        add("shift", 12.25, 3.7, 2.25)
    return _keyboard(middle)


def keyboard_geometry(layout):
    return ansi_keyboard() if layout == "ansi" else iso_keyboard()


KB_W, KB_H = 14.5, 5.7
RETURN_PATH = [(13.5, 1.7), (14.5, 1.7), (14.5, 3.7), (13.75, 3.7), (13.75, 2.7), (13.5, 2.7)]


def return_path(layout):
    """Outline of the L-shaped ISO Return key; None on ANSI, where Return is an ordinary key."""
    return None if layout == "ansi" else RETURN_PATH

# Qualitative palette (light fills, dark text), one colour per wire.
PALETTE = ["#a6cee3", "#fdbf6f", "#fb9a99", "#b2df8a", "#cab2d6", "#ffff99", "#8dd3c7", "#fccde5", "#bebada",
           "#e5c494", "#ccebc5", "#ffd92f"]


# SVG / text builders ------------------------------------------------------------------------------------------

def _svg(w, h, body, title):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w:.0f} {h:.0f}" width="{w:.0f}" height="{h:.0f}" '
            f'font-family="-apple-system, Helvetica, Arial, sans-serif" role="img" aria-label="{html.escape(title)}">'
            f'<title>{html.escape(title)}</title><rect width="100%" height="100%" fill="#fff"/>{body}</svg>\n')


def keyboard_svg(kb, by, title, highlight=None, unit=56):
    """Physical keyboard. by = 'row' or 'column' colours each key by that wire."""
    ids = kb.rows if by == "row" else kb.columns
    colour = {w: PALETTE[i % len(PALETTE)] for i, w in enumerate(ids)}
    pad = 12
    out = []
    for label, x, y, w, h, kid in keyboard_geometry(kb.layout):
        rx, ry, rw, rh = pad + x * unit + 2, pad + 30 + y * unit + 2, w * unit - 4, h * unit - 4
        if kid in kb.pos:
            r, c = kb.pos[kid]
            wire = r if by == "row" else c
            fill = colour[wire]
            out.append(f'<rect x="{rx:.1f}" y="{ry:.1f}" width="{rw:.1f}" height="{rh:.1f}" rx="6" fill="{fill}" '
                       f'stroke="#333" stroke-width="1"/>')
            size = 20 if len(label) == 1 else 14
            out.append(f'<text x="{rx + rw / 2:.1f}" y="{ry + rh * 0.48:.1f}" font-size="{size}" text-anchor="middle" '
                       f'dominant-baseline="middle" fill="#111" font-weight="600">{html.escape(label)}</text>')
            tag = r if by == "row" else f"col {c}"
            out.append(f'<text x="{rx + rw / 2:.1f}" y="{ry + rh - 7:.1f}" font-size="9.5" text-anchor="middle" '
                       f'fill="#222">{html.escape(tag)}</text>')
        elif kid in kb.unplaced:
            # On the keyboard, but its place in the matrix is not known: dashed, legend in full size.
            out.append(f'<rect x="{rx:.1f}" y="{ry:.1f}" width="{rw:.1f}" height="{rh:.1f}" rx="6" fill="#f2f2f2" '
                       f'stroke="#888" stroke-width="1.2" stroke-dasharray="4 3"/>')
            out.append(f'<text x="{rx + rw / 2:.1f}" y="{ry + rh * 0.48:.1f}" font-size="20" text-anchor="middle" '
                       f'dominant-baseline="middle" fill="#777" font-weight="600">{html.escape(label)}</text>')
            out.append(f'<text x="{rx + rw / 2:.1f}" y="{ry + rh - 7:.1f}" font-size="9" text-anchor="middle" '
                       f'fill="#777">unknown</text>')
        else:
            out.append(f'<rect x="{rx:.1f}" y="{ry:.1f}" width="{rw:.1f}" height="{rh:.1f}" rx="6" fill="#f2f2f2" '
                       f'stroke="#bbb" stroke-width="1"/>')
            out.append(f'<text x="{rx + rw / 2:.1f}" y="{ry + rh / 2:.1f}" font-size="10" text-anchor="middle" '
                       f'dominant-baseline="middle" fill="#999">{html.escape(label)}</text>')
    if return_path(kb.layout):
        pts = " ".join(f"{pad + x * unit:.1f},{pad + 30 + y * unit:.1f}" for x, y in return_path(kb.layout))
        out.append(f'<polygon points="{pts}" fill="#f2f2f2" stroke="#bbb" transform="translate(0,0)"/>')
        out.append(f'<text x="{pad + 14 * unit:.1f}" y="{pad + 30 + 2.2 * unit:.1f}" font-size="10" text-anchor="middle" '
                   f'fill="#999">return</text>')
    out.append(f'<text x="{pad}" y="{pad + 12}" font-size="15" font-weight="600">{html.escape(title)}</text>')
    unplaced = " and ".join(kb.unplaced[k]["label"] for k in kb.unplaced)
    grey = (f"Grey keys are not mapped. Dashed: {unplaced}, whose wires are unknown on this keyboard." if unplaced
            else "Grey keys are not mapped.")
    out.append(f'<text x="{pad + KB_W * unit:.1f}" y="{pad + 12}" font-size="11" text-anchor="end" fill="#666">'
               f'{html.escape(grey)}</text>')
    return _svg(KB_W * unit + 2 * pad, KB_H * unit + 2 * pad + 30, "".join(out), title)


def matrix_svg(kb, title, pressed=(), phantom=None, note=None, cell=58):
    """The matrix as a grid. pressed: keys drawn as held; phantom: spot drawn as the fourth corner."""
    left, top = 78, 58
    w = left + cell * len(kb.columns) + 16
    h = top + cell * len(kb.rows) + (44 if note else 16)
    out = [f'<text x="12" y="22" font-size="15" font-weight="600">{html.escape(title)}</text>']
    for j, c in enumerate(kb.columns):
        out.append(f'<text x="{left + j * cell + cell / 2}" y="{top - 10}" font-size="12" text-anchor="middle" '
                   f'fill="#444">col {html.escape(c)}</text>')
    pressed = list(dict.fromkeys(kb.keys_of(pressed)))  # keep the caller's order so the output is reproducible
    labels = []
    for i, r in enumerate(kb.rows):
        y = top + i * cell
        out.append(f'<text x="{left - 8}" y="{y + cell / 2 + 4}" font-size="12" text-anchor="end" fill="#444">'
                   f'row {html.escape(r)}</text>')
        for j, c in enumerate(kb.columns):
            x = left + j * cell
            p = (r, c)
            fill, stroke, sw, dash = "#fff", "#ccc", 1, ""
            text, tcol, weight = "", "#111", "600"
            if p in kb.at:
                k = kb.at[p]
                fill = "#eef3fb" if not pressed else "#f6f6f6"
                text = kb.label(k)
                if k in pressed:
                    fill, stroke, sw = "#3b78d8", "#1d4e9e", 2
                    tcol = "#fff"
            elif p in kb.unidentified:
                fill, text, tcol, weight = "url(#hatch)", "?", "#666", "400"
            if phantom and p == tuple(phantom):
                stroke, sw, dash = "#d62728", 3, ' stroke-dasharray="6 4"'
            out.append(f'<rect x="{x + 2}" y="{y + 2}" width="{cell - 4}" height="{cell - 4}" rx="5" fill="{fill}" '
                       f'stroke="{stroke}" stroke-width="{sw}"{dash}/>')
            if text:
                size = 18 if len(text) == 1 else 12
                labels.append(f'<text x="{x + cell / 2}" y="{y + cell / 2 + 1}" font-size="{size}" text-anchor="middle" '
                              f'dominant-baseline="middle" fill="{tcol}" font-weight="{weight}">{html.escape(text)}</text>')
    if len(pressed) == 3:
        t = tuple(pressed)
        s = kb.l_shape(*t)
        if s:
            corner = s[0]
            others = [k for k in t if k != corner]

            def centre(spot):
                r, c = spot
                return left + kb.columns.index(c) * cell + cell / 2, top + kb.rows.index(r) * cell + cell / 2
            cx, cy = centre(kb.pos[corner])
            for o in others:
                ox, oy = centre(kb.pos[o])
                out.append(f'<line x1="{cx}" y1="{cy}" x2="{ox}" y2="{oy}" stroke="#1d4e9e" stroke-width="4" '
                           f'stroke-opacity="0.45" stroke-linecap="round"/>')
            fx, fy = centre(s[1])
            for o in others:
                ox, oy = centre(kb.pos[o])
                out.append(f'<line x1="{fx}" y1="{fy}" x2="{ox}" y2="{oy}" stroke="#d62728" stroke-width="2" '
                           f'stroke-dasharray="5 4" stroke-opacity="0.7"/>')
    out += labels
    if note:
        out.append(f'<text x="12" y="{h - 16}" font-size="13" fill="#333">{html.escape(note)}</text>')
    defs = ('<defs><pattern id="hatch" width="6" height="6" patternUnits="userSpaceOnUse" '
            'patternTransform="rotate(45)"><rect width="6" height="6" fill="#f4f4f4"/>'
            '<line x1="0" y1="0" x2="0" y2="6" stroke="#cfcfcf" stroke-width="2"/></pattern></defs>')
    return _svg(w, h, defs + "".join(out), title)


def heatmap_svg(kb, title, cell=15):
    """For every pair of held keys, how many third keys the keyboard drops."""
    keys = physical_order(kb)
    n = len(keys)
    counts = {}
    for a, b in itertools.combinations(keys, 2):
        counts[(a, b)] = counts[(b, a)] = len(kb.dropped_when_holding(a, b))
    top_n = max(counts.values())
    left, top = 40, 60
    out = [f'<text x="12" y="22" font-size="15" font-weight="600">{html.escape(title)}</text>',
           f'<text x="12" y="42" font-size="11" fill="#555">Hold the key of the row and the key of the column: '
           f'the number is how many other keys can not be added (darker = more).</text>']
    for i, k in enumerate(keys):
        lab = html.escape(kb.label(k))
        out.append(f'<text x="{left - 4}" y="{top + i * cell + cell * 0.72}" font-size="10" text-anchor="end">{lab}</text>')
        out.append(f'<text x="{left + i * cell + cell / 2}" y="{top - 4}" font-size="10" text-anchor="middle">{lab}</text>')
    for i, a in enumerate(keys):
        for j, b in enumerate(keys):
            if a == b:
                continue
            v = counts[(a, b)]
            if v == 0:
                colour = "#f7f7f7"
            else:
                t = v / top_n
                colour = f"rgb({int(255 - 180 * t)},{int(235 - 200 * t)},{int(235 - 200 * t)})"
            out.append(f'<rect x="{left + j * cell}" y="{top + i * cell}" width="{cell - 1}" height="{cell - 1}" '
                       f'fill="{colour}"><title>{html.escape(kb.label(a))} + {html.escape(kb.label(b))}: {v} dropped</title></rect>')
    return _svg(left + n * cell + 16, top + n * cell + 16, "".join(out), title)


def physical_order(kb):
    order = []
    for label, x, y, w, h, kid in sorted(keyboard_geometry(kb.layout), key=lambda k: (round(k[2], 1), k[1])):
        if kid in kb.pos and kid not in order:
            order.append(kid)
    return order


def triples_csv(kb):
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(["key_1", "key_2", "key_3", "corner", "fourth_corner_row", "fourth_corner_column", "fourth_corner_holds"])
    rank = {k: i for i, k in enumerate(physical_order(kb))}
    for t, corner, spot in sorted(kb.all_blocked_triples(), key=lambda r: sorted(rank[k] for k in r[0])):
        ks = sorted(t, key=rank.get)
        holds = kb.label(kb.at[spot]) if spot in kb.at else "unidentified"
        w.writerow([kb.label(k) for k in ks] + [kb.label(corner), spot[0], spot[1], holds])
    return buf.getvalue()


def md_key(label):
    """A key label as Markdown inline code (the backtick key needs double backticks)."""
    return "`` ` ``" if "`" in label else f"`{label}`"


def dropped_md(kb):
    order = physical_order(kb)
    lines = ["# Dropped keys by held pair", "",
             "Hold the two keys on the left; the keys on the right can not be added (the keyboard drops them).",
             "Pairs not listed can be combined with any third key. Generated by `python3 kbmatrix.py build`.", "",
             "| Held | Dropped when added |", "|---|---|"]
    rows = 0
    for a, b in itertools.combinations(order, 2):
        d = kb.dropped_when_holding(a, b)
        if d:
            rows += 1
            lines.append(f"| {md_key(kb.label(a))} + {md_key(kb.label(b))} | " + " ".join(md_key(kb.label(x)) for x in d) + " |")
    lines += ["", f"{rows} pairs drop at least one third key.", ""]
    return "\n".join(lines)


def keys_md(kb):
    counts = {k: 0 for k in kb.order}
    for t, _, _ in kb.all_blocked_triples():
        for k in t:
            counts[k] += 1
    lines = ["# Keys and their wires", "",
             "Every mapped key, its wires, and how many dropped 3-key combinations it is part of.",
             "Generated by `python3 kbmatrix.py build`.", "",
             "| Key | macOS key code | kVK constant | Row wire | Column wire | In dropped triples |",
             "|---|---|---|---|---|---|"]
    for k in physical_order(kb):
        d = kb.keys[k]
        lines.append(f"| {md_key(d['label'])}{' (' + d['note'] + ')' if d.get('note') else ''} | {d['keycode']} | "
                     f"`{d['kvk']}` | {d['row']} | {d['column']} | {counts[k]} |")
    return "\n".join(lines) + "\n"


def web_bundle(kbs):
    """Data and drawing of each keyboard for the page: window.KB.iso, window.KB.ansi."""
    payload = {}
    for kb in kbs:
        geometry = [{"label": l, "x": x, "y": y, "w": w, "h": h, "id": kid}
                    for l, x, y, w, h, kid in keyboard_geometry(kb.layout)]
        payload[kb.layout] = {"name": LAYOUT_NAMES[kb.layout], "data": kb.data, "geometry": geometry,
                              "returnPath": return_path(kb.layout), "size": [KB_W, KB_H]}
    return "// Generated by `python3 kbmatrix.py build`.\nwindow.KB = " + json.dumps(payload, ensure_ascii=False) + ";\n"


def data_json(data):
    return json.dumps(data, indent=1, ensure_ascii=False) + "\n"


def build(kb, out=DOCS, data_out=DATA):
    """Writes docs/ and the derived US data from the measured ISO data. Returns ("docs" | "data", name) pairs."""
    if kb.layout != "iso":
        raise ValueError("build works from the measured ISO data (the US data is derived from it)")
    ansi_data = derive_ansi(kb.data)
    ansi = Matrix(ansi_data)
    os.makedirs(out, exist_ok=True)
    os.makedirs(data_out, exist_ok=True)
    files = {
        "keyboard-columns.svg": keyboard_svg(kb, "column", "MacBookPro18,1 ISO keyboard: column wires"),
        "keyboard-rows.svg": keyboard_svg(kb, "row", "MacBookPro18,1 ISO keyboard: row wires (each key names its row)"),
        "keyboard-columns-ansi.svg": keyboard_svg(ansi, "column", "US (ANSI) keyboard: column wires, not measured"),
        "keyboard-rows-ansi.svg": keyboard_svg(ansi, "row", "US (ANSI) keyboard: row wires, not measured"),
        "matrix.svg": matrix_svg(kb, "The matrix: rows and columns of wires (? = a key that is not mapped)"),
        "example-dropped.svg": matrix_svg(
            kb, "J + H + M is dropped", pressed=["J", "H", "M"], phantom=kb.pos["N"],
            note="J shares a row with H and a column with M. The fourth corner holds N, so the keyboard drops the chord."),
        "example-registers.svg": matrix_svg(
            kb, "J + M + X registers", pressed=["J", "M", "X"], phantom=("home", "2"),
            note="M shares a column with J and a row with X. The fourth corner is an empty spot, so all three register."),
        "dropped-by-pair.svg": heatmap_svg(kb, "Keys dropped for each held pair"),
        "dropped-triples.csv": triples_csv(kb),
        "dropped-by-pair.md": dropped_md(kb),
        "keys.md": keys_md(kb),
        "kb-data.js": web_bundle([kb, ansi]),
    }
    for name, text in files.items():
        with open(os.path.join(out, name), "w", encoding="utf-8") as f:
            f.write(text)
    ansi_name = os.path.basename(ANSI_DATA)
    with open(os.path.join(data_out, ansi_name), "w", encoding="utf-8") as f:
        f.write(data_json(ansi_data))
    return [("docs", n) for n in sorted(files)] + [("data", ansi_name)]


# Command line ---------------------------------------------------------------------------------------------------

def main(argv=None):
    p = argparse.ArgumentParser(description="Which key combinations the MacBook Pro 2021 keyboard registers.")
    p.add_argument("--layout", choices=["iso", "ansi", "us"], default="iso",
                   help="iso: the measured Canadian French keyboard (default); ansi or us: the US keyboard, derived "
                        "from it (not measured)")
    p.add_argument("--data", help="wiring file (JSON); overrides --layout")
    sub = p.add_subparsers(dest="cmd", required=True)
    c = sub.add_parser("check", help="does this combination register? (names, labels, key codes)")
    c.add_argument("keys", nargs="+")
    h = sub.add_parser("hold", help="keys that can't be added while holding two keys")
    h.add_argument("keys", nargs=2)
    t = sub.add_parser("triples", help="every dropped 3-key combination")
    t.add_argument("--csv", action="store_true")
    v = sub.add_parser("validate", help="replay the recorded observations")
    v.add_argument("-v", "--verbose", action="store_true")
    sub.add_parser("keys", help="key names you can use")
    sub.add_parser("build", help="regenerate docs/")
    a = p.parse_args(argv)
    kb = load(a.data or LAYOUT_DATA["ansi" if a.layout == "us" else a.layout])
    try:
        return run(kb, a)
    except (KeyError, ValueError) as e:
        print(e.args[0], file=sys.stderr)
        return 2


def run(kb, a):
    if a.cmd == "check":
        keys = kb.keys_of(a.keys)
        print(kb.explain(keys))
        return 0 if kb.registers(keys) else 1
    if a.cmd == "hold":
        x, y = kb.keys_of(a.keys)
        d = kb.dropped_when_holding(x, y)
        print(f"Holding {kb.label(x)} + {kb.label(y)}: " + ("every other key can be added." if not d else
              f"{len(d)} keys are dropped: " + " ".join(kb.label(k) for k in d)))
        return 0
    if a.cmd == "triples":
        if a.csv:
            sys.stdout.write(triples_csv(kb))
        else:
            rows = kb.all_blocked_triples()
            for t, corner, spot in rows:
                print(" + ".join(kb.label(k) for k in t))
            n = len(kb.order)
            print(f"{len(rows)} of {n * (n - 1) * (n - 2) // 6} 3-key combinations are dropped.")
        return 0
    if a.cmd == "validate":
        if kb.data.get("derived_from"):
            print(f"Nothing to replay: this keyboard was not measured. Its data is derived from "
                  f"{kb.data['derived_from']}, and the observations in data/observations/ are of that keyboard.")
            return 0
        ok = True
        for group, files in (("used to work out the wiring", FITTED), ("predicted before they were run", PREDICTED)):
            e, total, bad = validate(kb, files)
            print(f"{e} of {total} observations {group} match the wiring.")
            for o in bad:
                print(f"   {o.source}: {o.label}: observed {'dropped' if o.blocked else 'registered'}")
            ok &= not bad or group.startswith("used")
        return 0 if ok else 1
    if a.cmd == "keys":
        for k in kb.order:
            d = kb.keys[k]
            print(f"{d['label']:6s} {k:10s} code:{d['keycode']:<3d} {d['kvk']:24s} {d['web_code']:13s} "
                  f"row {d['row']:8s} column {d['column']}")
        for k, d in kb.unplaced.items():
            print(f"{d['label']:6s} {k:10s} code:{d['keycode']:<3d} {d['kvk']:24s} {d['web_code']:13s} "
                  f"not placed: {d['note']}")
        return 0
    if a.cmd == "build":
        for d, f in build(kb):
            print(f"wrote {d}/{f}")
        return 0
    return 2


if __name__ == "__main__":
    sys.exit(main())
